name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Setup .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0' # Update to your project's .NET version

      # Step 3: Install dependencies and build project
      - name: Install Dependencies and Build
        run: |
          dotnet restore
          dotnet build --no-restore --configuration Release

      # Step 4: Run .NET tests
      - name: Run .NET Tests
        run: |
          dotnet test --no-build --configuration Release

  python-tests:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Setup Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # Adjust version as needed

      # Step 3: Install dependencies
      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      # Step 4: Run Python tests
      - name: Run Python Tests
        run: |
          pytest
