name: CargoHub CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened

permissions:
  contents: read
  security-events: write  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Debug directory structure (optional)
      - name: List Files
        run: ls -R

      # Set up .NET SDK for .NET 8.0
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      # Restore .NET dependencies
      - name: Restore dependencies
        run: dotnet restore

      # Initialize CodeQL with the default setup (auto-detection of languages)
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3

      # Build the Solution (Required for CodeQL)
      - name: Build Solution
        run: dotnet build --configuration Release

      # Run CodeQL Analysis (default queries, no custom configuration)
      - name: Run CodeQL Analysis
        uses: github/codeql-action/analyze@v3

