name: CargoHub CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Debug directory structure
      - name: List Files
        run: ls -R
        working-directory: .

      # Set up .NET SDK for .NET 8.0
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      # Restore .NET dependencies for the main app
      - name: Restore dependencies (Main App)
        run: dotnet restore
        working-directory: CargoHubV2/Cargohub V2/Cargohub V2

      # Build the main application
      - name: Build (Main App)
        run: dotnet build --no-restore --configuration Release
        working-directory: CargoHubV2/Cargohub V2/Cargohub V2

      # Run unit tests for the UnitTests project (after build is successful)
      - name: Run unit tests
        run: dotnet test --configuration Release --no-build --collect:"XPlat Code Coverage"
        working-directory: ./UnitTests

      # Publish test results (Optional, for reporting in GitHub Actions UI)
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: $(System.DefaultWorkingDirectory)/TestResults
